# Generated by Django 6.1.1 on 2026-10-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='bullets',
            field=models.TextField(blank=True, help_text='One bullet point per line.'),
        ),
        migrations.AlterField(
            model_name='service',
            name='summary',
            field=models.CharField(help_text="Short tagline shown under the title, e.g. 'A clear identity for your business.'", max_length=255),
        ),
    ]
