# Generated by Django 6.1.1 on 2026-10-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_service_icon_service_bullets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_slug',
            field=models.CharField(blank=True, choices=[('brand-identity', 'Brand Identity'), ('content-creation', 'Content Creation'), ('websites', 'Websites'), ('business-consulting', 'Business Consulting')], help_text='Which icon graphic to show for this service.', max_length=30),
        ),
    ]
